import { Feature } from '@/components/ui/label';
import { isFeatureActive } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'A.P.P.S',
  description: 'Generated by A.P.P.S System by cpe-coder',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {!isFeatureActive() ? <Feature /> : children}
        <Toaster position="bottom-right" richColors={true} theme="light" />
      </body>
    </html>
  );
}
